'use client'

import * as React from 'react'
import { ChevronRight } from 'lucide-react'
import type { ExceptionCategory, ExceptionRecord } from '@/lib/domain/types'
import { Card, CardHeader, DrilldownLink, SeverityChip, StatusDot } from '@/components/ui/primitives'
import { EXCEPTION_CATEGORY_LABEL } from '@/lib/domain/exceptions'
import { useSession } from '@/lib/state/session-context'
import { formatIst, formatNumber } from '@/lib/utils'
import { cn } from '@/lib/utils'

const CATEGORY_ORDER: ExceptionCategory[] = ['CAPACITY', 'TEMPERATURE', 'INVENTORY', 'OPERATIONS', 'DATA_QUALITY']

function shortValue(exception: ExceptionRecord): string {
  if (exception.actual === null) return 'N/A'
  if (exception.unit === '%') return `${exception.actual.toFixed(1)}%`
  if (exception.unit.startsWith('pp')) return `${exception.actual > 0 ? '+' : ''}${exception.actual.toFixed(1)} pp`
  if (exception.unit === '°C') return `${exception.actual.toFixed(1)} °C`
  return `${formatNumber(exception.actual)} ${exception.unit}`
}

/**
 * Exception list.
 *
 * Used both as the control tower's "what needs attention today" panel and as
 * the body of the dedicated Exceptions screen. Every row opens the detail
 * drawer - there are no dead ends.
 */
export function ExceptionList({
  exceptions,
  onSelect,
  limit,
  title = 'Exceptions',
  subtitle,
  showCategoryFilter = false,
  showAllHref,
}: {
  exceptions: ExceptionRecord[]
  onSelect: (exception: ExceptionRecord) => void
  limit?: number
  title?: string
  subtitle?: string
  showCategoryFilter?: boolean
  showAllHref?: string
}) {
  const { exceptionStatus } = useSession()
  const [category, setCategory] = React.useState<ExceptionCategory | 'ALL'>('ALL')

  const filtered = React.useMemo(
    () => (category === 'ALL' ? exceptions : exceptions.filter((e) => e.category === category)),
    [exceptions, category],
  )
  const shown = limit ? filtered.slice(0, limit) : filtered

  const counts = React.useMemo(() => {
    const map = new Map<ExceptionCategory, number>()
    for (const exception of exceptions) {
      map.set(exception.category, (map.get(exception.category) ?? 0) + 1)
    }
    return map
  }, [exceptions])

  return (
    <Card className="flex h-full flex-col">
      <CardHeader
        title={title}
        subtitle={subtitle ?? `${exceptions.length} open · ${exceptions.filter((e) => e.severity === 'critical').length} critical`}
        tip="Exceptions are generated by rules over the reported figures, not entered by hand. Each carries the metric, the threshold it crossed, the variance, the accountable owner and a recommended action."
      />

      {showCategoryFilter ? (
        <div className="flex flex-wrap gap-1 border-b border-hairline px-3 py-2 no-print">
          <CategoryTab label="All" count={exceptions.length} active={category === 'ALL'} onClick={() => setCategory('ALL')} />
          {CATEGORY_ORDER.map((id) => (
            <CategoryTab
              key={id}
              label={EXCEPTION_CATEGORY_LABEL[id]}
              count={counts.get(id) ?? 0}
              active={category === id}
              onClick={() => setCategory(id)}
            />
          ))}
        </div>
      ) : null}

      <ul className="divide-y divide-hairline">
        {shown.length === 0 ? (
          <li className="px-4 py-8 text-center text-[12px] text-ink-muted">No exceptions in this category.</li>
        ) : (
          shown.map((exception) => {
            const status = exceptionStatus[exception.id] ?? exception.status
            return (
              <li key={exception.id}>
                <button
                  type="button"
                  onClick={() => onSelect(exception)}
                  className="group flex w-full items-start gap-2.5 px-4 py-2.5 text-left transition-colors hover:bg-brand-50/50"
                >
                  <SeverityChip severity={exception.severity} className="mt-0.5 shrink-0" />
                  <div className="min-w-0 flex-1">
                    <p className="flex flex-wrap items-baseline gap-x-1.5 text-[12px] font-semibold text-ink">
                      <span>
                        {exception.parkAndPaySiteId
                          ? `P&P · ${exception.regionId ?? 'Network'}`
                          : (exception.facilityId ?? exception.regionId ?? 'Network')}
                      </span>
                      <span className="font-normal text-ink-muted">{exception.metricLabel}</span>
                      <span className="tnum font-bold text-ink">{shortValue(exception)}</span>
                      {exception.threshold !== null ? (
                        <span className="tnum text-[10.5px] font-normal text-ink-faint">
                          vs threshold {exception.unit === '%' ? `${exception.threshold}%` : formatNumber(exception.threshold)}
                        </span>
                      ) : null}
                    </p>
                    <p className="mt-0.5 line-clamp-2 text-[11px] leading-relaxed text-ink-muted">{exception.reason}</p>
                    <p className="mt-1 flex flex-wrap items-center gap-x-2 text-[10px] text-ink-faint">
                      <span className="rounded border border-hairline bg-slate-50 px-1 py-0.5 font-semibold uppercase tracking-wide">
                        {EXCEPTION_CATEGORY_LABEL[exception.category]}
                      </span>
                      <span>{exception.owner}</span>
                      <span>{formatIst(exception.raisedAt, 'dd MMM HH:mm')}</span>
                      <span className="inline-flex items-center gap-1">
                        <StatusDot status={status === 'OPEN' ? 'critical' : status === 'RESOLVED' ? 'healthy' : 'watch'} />
                        {status.charAt(0) + status.slice(1).toLowerCase()}
                      </span>
                    </p>
                  </div>
                  <ChevronRight
                    className="mt-1 h-3.5 w-3.5 shrink-0 text-ink-faint transition-transform group-hover:translate-x-0.5 group-hover:text-brand-500"
                    strokeWidth={2.5}
                    aria-hidden
                  />
                </button>
              </li>
            )
          })
        )}
      </ul>

      {showAllHref && limit && filtered.length > limit ? (
        <div className="mt-auto border-t border-hairline px-4 py-2 no-print">
          <DrilldownLink href={showAllHref}>View all {filtered.length} exceptions</DrilldownLink>
        </div>
      ) : null}
    </Card>
  )
}

function CategoryTab({
  label,
  count,
  active,
  onClick,
}: {
  label: string
  count: number
  active: boolean
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-md border px-2 py-1 text-[11.5px] font-medium transition-colors',
        active ? 'border-brand-300 bg-brand-50 text-brand-700' : 'border-hairline bg-surface text-ink-muted hover:bg-slate-50',
      )}
    >
      {label}
      <span className={cn('tnum rounded px-1 text-[10px] font-bold', active ? 'bg-brand-500 text-white' : 'bg-slate-100 text-ink-muted')}>
        {count}
      </span>
    </button>
  )
}
