'use client'

import * as React from 'react'
import Link from 'next/link'
import { ArrowRight, Lightbulb } from 'lucide-react'
import type { Insight } from '@/lib/domain/types'
import { Card, CardHeader, SeverityChip } from '@/components/ui/primitives'
import { SEVERITY_RANK } from '@/lib/config/thresholds'

/**
 * Management insights.
 *
 * Generated by rules in src/lib/domain/insights.ts from the same figures the
 * screens render. Each card names the calculation it came from, so nothing
 * here is an assertion the reader cannot check. No language model is involved
 * and the panel says so rather than implying one.
 */
export function ManagementInsights({ insights, limit }: { insights: Insight[]; limit?: number }) {
  const ordered = React.useMemo(
    () => [...insights].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]).slice(0, limit),
    [insights, limit],
  )

  return (
    <Card className="flex h-full flex-col">
      <CardHeader
        title={
          <span className="inline-flex items-center gap-1.5">
            <Lightbulb className="h-3.5 w-3.5 text-brand-500" strokeWidth={2.25} aria-hidden />
            Management Insights
          </span>
        }
        subtitle="Rule-based, derived from today’s figures"
        tip="These statements are produced by deterministic rules over the same data the dashboard renders — thresholds, trends and rankings. There is no language model or predictive model behind them, and each one names the calculation it came from."
      />
      <ul className="divide-y divide-hairline">
        {ordered.map((insight) => {
          const content = (
            <>
              <div className="flex items-start gap-2">
                <SeverityChip severity={insight.severity} className="mt-0.5 shrink-0" />
                <p className="min-w-0 flex-1 text-[12px] leading-relaxed text-ink-soft">{insight.text}</p>
                {insight.href ? (
                  <ArrowRight
                    className="mt-0.5 h-3 w-3 shrink-0 text-brand-500 transition-transform group-hover:translate-x-0.5"
                    strokeWidth={2.5}
                    aria-hidden
                  />
                ) : null}
              </div>
              <p className="mt-1 pl-[4.6rem] text-[10px] text-ink-faint">Source: {insight.source}</p>
            </>
          )
          return (
            <li key={insight.id}>
              {insight.href ? (
                <Link href={insight.href} className="group block px-4 py-2.5 transition-colors hover:bg-brand-50/50">
                  {content}
                </Link>
              ) : (
                <div className="px-4 py-2.5">{content}</div>
              )}
            </li>
          )
        })}
      </ul>
    </Card>
  )
}
